# Generated by Django 5.2.5 on 2025-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foundpetreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('investigating', 'Under investigation'), ('matched', 'Matched with potential owner'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('investigating', 'Under investigation'), ('matched', 'Matched with potential owner'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=32),
        ),
    ]
