# Generated by Django 5.2.8 on 2025-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0002_foundpetreport_admin_notes_foundpetreport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpetreport',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
