# Generated by Django 5.2.8 on 2025-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0003_alter_foundpetreport_photo_alter_lostpetreport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='vaccinated',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
