# Generated by Django 5.2.8 on 2025-12-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0004_lostpetreport_pincode_lostpetreport_vaccinated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('household_info', models.TextField(blank=True)),
                ('experience_with_pets', models.TextField()),
                ('reason_for_adopting', models.TextField()),
                ('has_other_pets', models.BooleanField(default=False)),
                ('other_pets_details', models.TextField(blank=True)),
                ('home_ownership', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent')], max_length=10)),
                ('preferred_meeting', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('adoption_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Pets.adoptionrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('age', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('photos', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='Pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('pet', 'requester')},
        ),
    ]
