# Generated by Django 5.2.8 on 2025-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0005_adoptionrequest_message_pet_adoptionrequest_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpetreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='found_pets/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lost_pets/%Y/%m/%d/'),
        ),
    ]
