# Generated by Django 5.2.8 on 2025-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0006_alter_foundpetreport_photo_alter_lostpetreport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='has_user_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foundpetreport',
            name='previous_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='has_user_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='previous_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
