# Generated by Django 5.2.8 on 2025-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0008_conversation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='found_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundpetreport',
            name='location_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='location_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='lost_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
