# Generated by Django 5.2.8 on 2025-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0009_foundpetreport_found_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='foundpetreport',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
