# Generated by Django 5.2.8 on 2025-12-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0010_foundpetreport_pincode_foundpetreport_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
