# Generated by Django 4.2.27 on 2025-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0011_foundpetreport_gender_lostpetreport_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pet_kind',
            field=models.CharField(blank=True, help_text='Type of context: lost, found, adoption, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pet_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
