# Generated by Django 5.2.5 on 2025-12-16 04:29

from django.db import migrations, models


def populate_pet_unique_ids(apps, schema_editor):
    """Populate pet_unique_id for existing FoundPetReport and LostPetReport records."""
    FoundPetReport = apps.get_model('Pets', 'FoundPetReport')
    LostPetReport = apps.get_model('Pets', 'LostPetReport')

    # Populate found pet reports
    for report in FoundPetReport.objects.all():
        if not report.pet_unique_id:
            report.pet_unique_id = f"FP{report.id:06d}"
            report.save(update_fields=['pet_unique_id'])

    # Populate lost pet reports
    for report in LostPetReport.objects.all():
        if not report.pet_unique_id:
            report.pet_unique_id = f"LP{report.id:06d}"
            report.save(update_fields=['pet_unique_id'])


def reverse_populate_pet_unique_ids(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0012_conversation_pet_id_conversation_pet_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='pet_unique_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='pet_unique_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(populate_pet_unique_ids, reverse_populate_pet_unique_ids),
    ]
