# Generated by Django 5.2.5 on 2025-12-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0013_add_pet_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pet_unique_id',
            field=models.CharField(blank=True, help_text='Unique public ID like FP000024 or LP000029 to avoid confusion between lost/found pets with same numeric ID', max_length=32, null=True),
        ),
    ]
