# Generated by Django 5.2.5 on 2025-12-16 04:33

from django.db import migrations, models


def populate_adoption_pet_unique_ids(apps, schema_editor):
    """Populate pet_unique_id for existing Pet (adoption) records."""
    Pet = apps.get_model('Pets', 'Pet')

    # Populate adoption pets
    for pet in Pet.objects.all():
        if not pet.pet_unique_id:
            pet.pet_unique_id = f"AP{pet.id:06d}"
            pet.save(update_fields=['pet_unique_id'])


def reverse_populate_adoption_pet_unique_ids(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0014_add_conversation_pet_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_unique_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(populate_adoption_pet_unique_ids, reverse_populate_adoption_pet_unique_ids),
    ]
