# Generated by Django 5.2.5 on 2025-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='reason_for_chat',
            field=models.TextField(blank=True, help_text="User's explanation for why they want to chat with admin", null=True),
        ),
    ]
