# Generated by Django 5.2.5 on 2025-12-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0019_add_reason_for_chat_to_conversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat_request', 'Chat Request'), ('chat_accepted', 'Chat Accepted'), ('chat_rejected', 'Chat Rejected'), ('chat_message', 'Chat Message'), ('chat_room_created', 'Chat Room Created'), ('chat_status_changed', 'Chat Status Changed'), ('chatroom_invitation', 'Chatroom Invitation'), ('chatroom_request_accepted', 'Chatroom Request Accepted'), ('chatroom_request_rejected', 'Chatroom Request Rejected'), ('adoption_request', 'Adoption Request'), ('adoption_status', 'Adoption Status'), ('report_status', 'Report Status')], max_length=32),
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pet_id', models.IntegerField(blank=True, null=True)),
                ('pet_unique_id', models.CharField(blank=True, max_length=32, null=True)),
                ('pet_kind', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, help_text='Purpose: Lost/Found/Reunite', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(help_text='Parent conversation this chatroom belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to='Pets.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatroomAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_unique_id', models.CharField(blank=True, help_text='Unique ID of the pet (FP/LP prefix)', max_length=32, null=True)),
                ('pet_kind', models.CharField(blank=True, help_text='lost or found', max_length=50)),
                ('role', models.CharField(default='requested_user', help_text='Role the user will have if accepted', max_length=50)),
                ('request_type', models.CharField(default='chatroom_join_request', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_invitations', to=settings.AUTH_USER_MODEL)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='Pets.chatroom')),
                ('pet', models.ForeignKey(blank=True, help_text='Pet related to this chatroom (can be Lost or Found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_access_requests', to='Pets.lostpetreport')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('chatroom', 'requested_user')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='chatroom_access_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Pets.chatroomaccessrequest'),
        ),
        migrations.CreateModel(
            name='ChatroomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_for', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False, help_text="True for system messages like 'User joined'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Pets.chatroom')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Pets.chatroommessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatroomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('requested_user', 'Requested User'), ('founded_user', 'Founded User')], max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Pets.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('chatroom', 'user')},
            },
        ),
    ]
