# Generated by Django 5.2.5 on 2025-12-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0020_alter_notification_notification_type_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroomaccessrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroomaccessrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Related conversation for chatroom creation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_access_requests', to='Pets.conversation'),
        ),
        migrations.AlterField(
            model_name='chatroomaccessrequest',
            name='chatroom',
            field=models.ForeignKey(blank=True, help_text='Chatroom (null if chatroom not yet created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='Pets.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroomaccessrequest',
            name='request_type',
            field=models.CharField(choices=[('chatroom_join_request', 'Chatroom Join Request'), ('chatroom_creation_request', 'Chatroom Creation Request')], default='chatroom_join_request', help_text='Type of request: join existing or create new chatroom', max_length=100),
        ),
    ]
