# Generated by Django 5.2.5 on 2025-12-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0022_add_attachment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='pet_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
