# Generated by Django 5.2.5 on 2025-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0023_chatroom_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='pet_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
