# Generated by Django 5.2.5 on 2025-12-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0025_add_has_tag_to_foundpetreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpetreport',
            name='adoption_pet',
            field=models.ForeignKey(blank=True, help_text='Reference to the adoption pet created from this found report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_found_report', to='Pets.pet'),
        ),
        migrations.AddField(
            model_name='foundpetreport',
            name='converted_to_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
