# Generated by Django 5.2.5 on 2025-12-10 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_lostpetreport_reporter_userprofile_landmark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('volunteering_preferences', models.TextField(blank=True, help_text='Comma-separated list of volunteering preferences')),
                ('availability', models.TextField(blank=True, help_text='Comma-separated list describing availability')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('moderate', 'Moderate'), ('experienced', 'Experienced'), ('professional', 'Professional vet / trainer')], max_length=20)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='volunteer_id_proofs/%Y/%m/%d/')),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
