# Generated by Django 5.2.5 on 2025-12-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_volunteerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrequest',
            name='volunteering_preferences',
        ),
    ]
